// app-client/__migration__/src/components/ActionList/ActionList.tsx
import React from 'react';

import Box from '@mui/material/Box';

const ActionList: React.FC<{
    actions?: Array<{ name: string, desc: string }>;
}> = ({ actions = [] }) => {
    const lastActionIndex = actions.length - 1;
    return (
        <div data-testid="action-list-container">
            {actions.map(({ name, desc }, i) => (
                <Box key={name}>
                    <b>{name}</b>{`: ${desc}${i < lastActionIndex ? ', ' : ''}`}
                </Box>
            ))}
        </div>
    );
};

export default ActionList;

// diploma-client/src/components/ActionList/ActionList.vue
<template>
    <v-row>
        <v-col v-for="({ name, desc }, i) in actions" :key="name" cols="12">
            <strong>{{ name }}</strong
            >: {{ desc }}{{ i < actions.length - 1 ? ', ' : '' }}
        </v-col>
    </v-row>
</template>

<script>
export default {
    name: 'ActionList',

    props: {
        actions: {
            type: Array,
            default: () => [],
        },
    },
};
</script>
