// app-client/__migration__/src/components/Auth/Auth.tsx
import { useState } from 'react';

import SignIn from '@/components/SignIn';
import SignUp from '@/components/SignUp';

export type Props = {
    onLoggedIn: () => void;
};

const Auth = ({ onLoggedIn }: Props) => {
    const [status, setStatus] = useState<'sign-up' | 'sign-in'>('sign-up');

    return status === 'sign-in'
        ? <SignIn onSwitch={() => setStatus('sign-up')} onLoggedIn={onLoggedIn} />
        : <SignUp onSwitch={() => setStatus('sign-in')} />;
};

export default Auth;

// diploma-client/src/modules/auth/index.vue
<template>
    <dnd-sign-in v-if="isSignIn" @sign-up="status = 'sign-up'" />
    <dnd-sign-up v-else @sign-in="status = 'sign-in'" />
</template>

<script>
import DndSignIn from '@/modules/auth/components/DndSignIn.vue';
import DndSignUp from '@/modules/auth/components/DndSignUp.vue';

export default {
    components: { DndSignIn, DndSignUp },
    data: () => ({
        status: 'sign-in',
    }),
    computed: {
        isSignIn() {
            return this.status === 'sign-in';
        },
    },
};
</script>
