// diploma-client/src/components/DownloadButton.vue
<template>
    <v-btn @click.stop="download">Download charsheet</v-btn>
</template>

<script>
import axios from 'axios';
import { useObjectURL } from '@/utils/coreUtils';
import { deserialize } from '@/utils/stringUtils';

export default {
    name: 'DownloadButton',
    props: {
        url: {
            type: String,
            required: true,
        },
    },
    methods: {
        async download() {
            const { data, headers } = await axios.get(this.url, { responseType: 'blob' });
            const contentDisposition = deserialize(headers['content-disposition']);
            const filename = contentDisposition['filename'] ?? 'charsheet.pdf';

            useObjectURL(data, (url) => {
                const link = document.createElement('a');

                link.setAttribute('href', url);
                link.setAttribute('download', filename);

                document.body.appendChild(link);

                link.click();
                link.remove();
            });
        },
    },
};
</script>

// app-client/src/components/DownloadButton/DownloadButton.tsx
import React, { MouseEventHandler } from 'react';

import Button from '@mui/material/Button';

import client from '@/api/client';
import { useObjectURL } from '@/utils/coreUtils.js';
import { deserialize } from '@/utils/stringUtils.js';

export type Props = {
    url: string;
    text: string;
};

const DownloadButton = ({ url, text }: Props) => {
    const download: MouseEventHandler = async () => {
        const { data, headers } = await client.get(url, { responseType: 'blob' });
        const contentDisposition = deserialize(headers['content-disposition']);
        const filename = contentDisposition['filename'] ?? 'charsheet.pdf';

        useObjectURL(data, (objectURL) => {
            const link = document.createElement('a');

            link.setAttribute('href', objectURL);
            link.setAttribute('download', filename);

            document.body.appendChild(link);

            link.click();
            link.remove();
        });
    };
    return (
        <Button onClick={download}>
            {text}
        </Button>
    );
};

export default DownloadButton;
